### ISSUE TITLE
体验minigpt4

### ISSUE THREAD

**Issue by awesometype** [WangRongsheng/Use-LLMs-in-Colab#10]
在colab成功运行了minigpt之后，怎么进行体验呢(网页或者命令行都行)
![image](https://github.com/WangRongsheng/Use-LLMs-in-Colab/assets/13300173/10f6f67e-bcda-4c59-a40d-a8bb322da299)

**Comment by WangRongsheng** [comment]
请确保你是google colab pro用户并且选用高性能GPU，如A100。

**Comment by awesometype** [comment]
> 请确保你是google colab pro用户并且选用高性能GPU，如A100。

确实，我不是pro用户
