### ISSUE TITLE
MiniGPT-4-LLaMA-7B部分缺少文件

### ISSUE THREAD

**Issue by LPARKOUR** [WangRongsheng/Use-LLMs-in-Colab#5]
当我准备跟着教程组合两个权重文件的时候看到原作者的readme更新了，里面是您的colab文件，跟着教程走一遍，发现确实13B的免费版的colab跑不动，接着看到您主页huggingface有7B的，试着在免费的colab上运行，发现提示报错：FileNotFoundError: [Errno 2] No such file or directory: 
'/content/MiniGPT-4/MiniGPT-4-LLaMA-7B/pytorch_model-00001-of-00002.bin'
对比了一下13B的文件，确实是少了这几个文件，接下来打算试试自己组合合成一下，试试能不能在免费的colab上跑，谢谢您所提供的文件！

**Comment by WangRongsheng** [comment]
正在上传，即将更新！

**Comment by LPARKOUR** [comment]
谢谢大哥！我刚刚尝试重新下载LLAMA-7B的原权重文件，发现好几种方法都下载不下来了，都报错访问不到了，下午还行的，期待您的更新！！谢谢！
