### ISSUE TITLE
Use_minigpt4.ipynb的pretrained_minigpt4下載連結錯誤

### ISSUE THREAD

**Issue by CYXup6** [WangRongsheng/Use-LLMs-in-Colab#6]
您好，在Use_minigpt4.ipynb裡面提供的pretrained_minigpt4連結無法正確下載model，發現要將連結修改成https://huggingface.co/wangrongsheng/MiniGPT4/resolve/main/pretrained_minigpt4.pth 即可正確下載.

感謝您！

**Comment by WangRongsheng** [comment]
Use_minigpt4.ipynb不提供自动下载，只是填写了路径
