### ISSUE TITLE
Encountered 1 file(s) that may not have been copied correctly on Windows: 	pytorch_model-00001-of-00002.bin

### ISSUE THREAD

**Issue by Mao-x-w** [WangRongsheng/Use-LLMs-in-Colab#7]
首先感谢老哥的ipynb。由于免费的colab内存不够，就尝试用合好的MiniGPT-4-LLaMA-7B。在尝试使用你再hugging face上提供的MiniGPT-4-LLaMA-7B，报上面错误。按道理colab上的是linux系统。上面报的是在windows，是不你那边是通过windows上传没成功？

**Comment by WangRongsheng** [comment]
收到，我会尽快测试一下

**Comment by WangRongsheng** [comment]
![image](https://user-images.githubusercontent.com/55651568/233848305-98e5aa5f-0589-437a-8064-fc0d5ce50c77.png)

一切都是正常的！

**Comment by LPARKOUR** [comment]
我也测试了一下7B的模型，新上传的没有该报错问题，但免费版的colab在加载checkpoint模型的时候，还是内存不够，自动中断停止了。看来就算是7B模型，免费版的colab内存也仍然是不够的。但无论如何最后还是感谢 @WangRongsheng 所提供的合成文件，谢谢！
