### ISSUE TITLE
error using minigpt4 colab notebook & 13B model

### ISSUE THREAD

**Issue by pdutoit2011** [WangRongsheng/Use-LLMs-in-Colab#8]
Loading checkpoint shards: 100% 3/3 [00:29<00:00,  9.93s/it]
Downloading (…)neration_config.json: 100% 137/137 [00:00<00:00, 169kB/s]
Loading LLAMA Done
Load 4 training prompts
Prompt Example 
###Human: <Img><ImageHere></Img> Take a look at this image and describe what you notice. ###Assistant: 
Load BLIP2-LLM Checkpoint: pretrained_minigpt4.pth
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /content/MiniGPT-4/demo.py:60 in <module>                                    │
│                                                                              │
│    57 model_config = cfg.model_cfg                                           │
│    58 model_config.device_8bit = args.gpu_id                                 │
│    59 model_cls = registry.get_model_class(model_config.arch)                │
│ ❱  60 model = model_cls.from_config(model_config).to('cuda:{}'.format(args.g │
│    61                                                                        │
│    62 vis_processor_cfg = cfg.datasets_cfg.cc_sbu_align.vis_processor.train  │
│    63 vis_processor = registry.get_processor_class(vis_processor_cfg.name).f │
│                                                                              │
│ /content/MiniGPT-4/minigpt4/models/mini_gpt4.py:265 in from_config           │
│                                                                              │
│   262 │   │   ckpt_path = cfg.get("ckpt", "")  # load weights of MiniGPT-4   │
│   263 │   │   if ckpt_path:                                                  │
│   264 │   │   │   print("Load BLIP2-LLM Checkpoint: {}".format(ckpt_path))   │
│ ❱ 265 │   │   │   ckpt = torch.load(ckpt_path, map_location="cpu")           │
│   266 │   │   │   msg = model.load_state_dict(ckpt['model'], strict=False)   │
│   267 │   │                                                                  │
│   268 │   │   return model                                                   │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/torch/serialization.py:815 in load   │
│                                                                              │
│    812 │   │   │   │   return _legacy_load(opened_file, map_location, _weigh │
│    813 │   │   │   except RuntimeError as e:                                 │
│    814 │   │   │   │   raise pickle.UnpicklingError(UNSAFE_MESSAGE + str(e)) │
│ ❱  815 │   │   return _legacy_load(opened_file, map_location, pickle_module, │
│    816                                                                       │
│    817                                                                       │
│    818 # Register pickling support for layout instances such as              │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/torch/serialization.py:1033 in       │
│ _legacy_load                                                                 │
│                                                                              │
│   1030 │   │   │   f"Received object of type \"{type(f)}\". Please update to │
│   1031 │   │   │   "functionality.")                                         │
│   1032 │                                                                     │
│ ❱ 1033 │   magic_number = pickle_module.load(f, **pickle_load_args)          │
│   1034 │   if magic_number != MAGIC_NUMBER:                                  │
│   1035 │   │   raise RuntimeError("Invalid magic number; corrupt file?")     │
│   1036 │   protocol_version = pickle_module.load(f, **pickle_load_args)      │
╰──────────────────────────────────────────────────────────────────────────────╯
UnpicklingError: invalid load key, '<'.

**Comment by pdutoit2011** [comment]
resolved, use:
# if you run 13B , Plaease Download Checkpoint Aligned with Vicuna 13B
!wget https://huggingface.co/wangrongsheng/MiniGPT4/resolve/main/pretrained_minigpt4.pth

**Comment by WangRongsheng** [comment]
maybe you can use this: https://colab.research.google.com/drive/1OK4kYsZphwt5DXchKkzMBjYF6jnkqh4R?usp=sharing

**Comment by pdutoit2011** [comment]
Thanks, solved it using the other wget linkSent from my phone-------- Original message --------From: MPU王荣胜 ***@***.***>Date: Thu, 11 May 2023, 16:05To: WangRongsheng/Use-LLMs-in-Colab ***@***.***>Cc: Philip du Toit ***@***.***>, Author ***@***.***>Subject: Re: [WangRongsheng/Use-LLMs-in-Colab] error using minigpt4 colab notebook & 13B model (Issue #8)
maybe you can use this: https://colab.research.google.com/drive/1OK4kYsZphwt5DXchKkzMBjYF6jnkqh4R?usp=sharing

**Comment by pdutoit2011** [comment]
btw, thanks for this great repo!
